export const serviceData = [
  {
    id: "1",
    img: "https://images.pexels.com/photos/580613/pexels-photo-580613.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    company: "Design",
    job: " Lorem ipsum .",
    address: "Kathmandu Nepal",
  },
  {
    id: "2",
    img: "https://images.pexels.com/photos/580613/pexels-photo-580613.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    company: "App development",
    job: " Lorem ipsum.",
    address: "Kathmandu Nepal",
  },
  {
    id: "3",
    img: "https://images.pexels.com/photos/580613/pexels-photo-580613.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    company: "Panting",
    job: " Lorem ipsum.",
    address: "Kathmandu Nepal",
  },
  {
    id: "4",
    img: "https://images.pexels.com/photos/580613/pexels-photo-580613.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    company: "2D Animation",
    job: " Lorem ipsum.",
    address: "Kathmandu Nepal",
  },
  {
    id: "5",
    img: "https://images.pexels.com/photos/580613/pexels-photo-580613.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    company: "Video editing",
    job: " Lorem ipsum.",
    address: "Kathmandu Nepal",
  },
  {
    id: "6",
    img: "https://images.pexels.com/photos/580613/pexels-photo-580613.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    company: "Graphic design",
    job: " Lorem ipsum.",
    address: "Kathmandu Nepal",
  },
  {
    id: "7",
    img: "https://images.pexels.com/photos/580613/pexels-photo-580613.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    company: "Graphic design",
    job: " Lorem ipsum.",
    address: "Kathmandu Nepal",
  },
  {
    id: "8",
    img: "https://images.pexels.com/photos/580613/pexels-photo-580613.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    company: "Graphic design",
    job: " Lorem ipsum.",
    address: "Kathmandu Nepal",
  },
  {
    id: "9",
    img: "https://images.pexels.com/photos/580613/pexels-photo-580613.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    company: "Graphic design",
    job: " Lorem ipsum.",
    address: "Kathmandu Nepal",
  },
  {
    id: "10",
    img: "https://images.pexels.com/photos/580613/pexels-photo-580613.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    company: "Graphic design",
    job: " Lorem ipsum.",
    address: "Kathmandu Nepal",
  },
  {
    id: "11",
    img: "https://images.pexels.com/photos/580613/pexels-photo-580613.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    company: "Graphic design",
    job: " Lorem ipsum.",
    address: "Kathmandu Nepal",
  },
  {
    id: "12",
    img: "https://images.pexels.com/photos/580613/pexels-photo-580613.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    company: "Graphic design",
    job: " Lorem ipsum .",
    address: "Kathmandu Nepal",
  },
];
